[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/admin-secret-92837"
  to = "/admin-secret-92837/"
  status = 301

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200
